<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <title>Calculate</title>
</head>
<body>


<div class="container">

    <form class="form-signin">
        <h2 class="form-signin-heading">Кредитный калькулятор</h2>
        <input type="number" name="sum" class="form-control" placeholder="Сумма покупки" required>
        <input type="number" name="payment" class="form-control" placeholder="Первоначальный взнос в процентах" required>
        <p>Срок кредитования</p>
        <div class="list-group">
            <select name="term">
                <option value="0,09">1 год  (9% годовых)</option>
                <option value="0,11">2 года (11% годовых)</option>
                <option value="0,13">3 года (13% годовых)</option>
                <option value="0,15">4 года (15% годовых)</option>
                <option value="0,17">5 лет (17% годовых)</option>
                <option value="0,19">6 лет (19% годовых)</option>
                <option value="0,21">7 лет (21% годовых)</option>
            </select>
        </div>
        <p><?=$errorMessage?></p>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Посчитать</button>
    </form>

</div> <!-- /container -->

</body>
</html>