<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <title>Calculate</title>
</head>
<body>

<div class="container">

    <form method="get" class="form-signin" >
        <h2 class="form-signin-heading">Кредитный калькулятор</h2>
        <input type="number" name="sum" class="form-control" placeholder="Сумма покупки" required>
        <input type="number" name="payment" class="form-control" placeholder="Первоначальный взнос в процентах" required>

        <p><?php
            If(!empty($errorMessage)){
                echo $errorMessage;
            }else{
                for($i=1; $i<=$month; $i++){
                    $result = $result - $payToMonth;
                    echo "{$i} месяц {$payToMonth}грн. {$result}грн. <br>";
                }
            } ?>
        </p>


        <h2>Срок кредитования</h2>
        <div class="list-group">
            <select name="term">
                <option value="1">1 год  (9% годовых)</option>
                <option value="2">2 года (11% годовых)</option>
                <option value="3">3 года (13% годовых)</option>
                <option value="4">4 года (15% годовых)</option>
                <option value="5">5 лет (17% годовых)</option>
                <option value="6">6 лет (19% годовых)</option>
                <option value="7">7 лет (21% годовых)</option>
            </select>
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Посчитать</button>
    </form>

</div> <!-- /container -->

</body>
</html>